### ISSUE TITLE
Introduce ability to load/construct a function registry that contains all functions allowed in a BFT dialect and their local name mapping

### ISSUE THREAD

**Issue by jacques-n** [substrait-io/substrait-go#28]
Let's create a FunctionRegistry that can be constructed for a BFT dialect. To start, just make it possible to build a repository of functions associated with a BFT dialect as well as lookup and list those functions. We'll likely enhance with more overload lookups. We should support both a local lookup (e.g. +) as well as a canonical lookup (e.g. ad_int:i8:i8).

**Comment by jacques-n** [comment]
As part of this, we should also be able to find the subset of operations that are binary operations.

**Comment by EpsilonPrime** [comment]
One thing I would have found useful would be a class that used such a [registry](https://github.com/voltrondata/spark-substrait-gateway/blob/main/src/gateway/converter/spark_functions.py) and assigned anchors to the URIs and function references as they were used during construction of a plan.  It may also be useful to include the type of the function in the registry (scalar, window, aggregate) depending on the intended use case for the registry.

**Comment by zeroshade** [comment]
Much of this registry handling (including assigned anchors and URIs etc.) is already handled via the https://github.com/substrait-io/substrait-go/blob/main/extensions/extension_mgr.go along with handling the lookup by type (scalar, window, aggregate) in the `Set` interface (https://github.com/substrait-io/substrait-go/blob/main/extensions/extension_mgr.go#L205).

I think the primary thing mentioned here that isn't already covered by these interfaces is being able to "find the subset of operations that are binary operations" etc.

**Comment by jacques-n** [comment]
> Much of this registry handling ...

Yup. This ticket should build on that work. The key here is we need to combine the bft dialect knowledge with the existing extension stuff.

**Comment by jacques-n** [comment]
Completed in #32
